### ISSUE TITLE
Uniswap between EVM and SOL

### ISSUE THREAD

**Issue by FireBolt2** [FireBolt2/solana#1]
I faced a problem when develop unisway between EVM and SOL
In the past I used x*y = const formula
but I realized nowadays x^2 + y^2 = const formula is used
How to implement?

**Comment by icanany** [comment]
Now that we have the intuition of what is happening, we will try to formalize a bit how prices evolves with trades. We know that the trade preserves the invariant x * y = K so we can write x₀ y₀ = K = (x₀ + δₓ) (y₀- δᵧ)

Users can also deposit liquidity. This should not affect the current price of liquidity, and therefore should preserve the proportion of asset A and B.

Given the current reserve (x, y) and the reserves user wants to add (xᵤ, yᵤ), we want to find (xₚ, yₚ) such that xₚ ≤ xᵤ, yₚ ≤ yᵤ:

**Comment by icanany** [comment]
can you provide detailed code?

**Comment by icanany** [comment]
you can use https://github.com/Dodecahedr0x/amm-tutorial
This github source is common Uniswap

**Comment by FireBolt2** [comment]
Thanks for your support
